# Site settings
title: mychii
email: mychii@me.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mychii.github.io" # the base hostname & protocol for your site
github_username:  mychii

# Build settings
markdown: kramdown
